### ISSUE TITLE
EXCEPTION CAUGHT BY SVG help me plis

### ISSUE THREAD

**Issue by boanergepro** [dnfield/flutter_svg#174]
```
I/flutter ( 4119): ══╡ EXCEPTION CAUGHT BY SVG ╞═══════════════════════════════════════════════════════════════════════
I/flutter ( 4119): The following StateError was thrown resolving a single-frame picture stream:
I/flutter ( 4119): Bad state: Could not parse "null" as a color.
I/flutter ( 4119): When the exception was thrown, this was the stack:
I/flutter ( 4119): #0      parseColor (package:flutter_svg/src/svg/colors.dart:78:3)
I/flutter ( 4119): #1      parseStroke (package:flutter_svg/src/svg/xml_parsers.dart:214:11)
I/flutter ( 4119): #2      parseStyle (package:flutter_svg/src/svg/xml_parsers.dart:370:13)
I/flutter ( 4119): #3      _Elements.g (package:flutter_svg/src/svg/parser_state.dart:99:7)
I/flutter ( 4119): #4      SvgParserState.parse (package:flutter_svg/src/svg/parser_state.dart:688:26)
I/flutter ( 4119): <asynchronous suspension>
I/flutter ( 4119): #5      SvgParser.parse (package:flutter_svg/parser.dart:14:60)
I/flutter ( 4119): <asynchronous suspension>
I/flutter ( 4119): #6      Svg.fromSvgString (package:flutter_svg/svg.dart:110:25)
I/flutter ( 4119): <asynchronous suspension>
I/flutter ( 4119): #7      Svg.svgPictureStringDecoder (package:flutter_svg/svg.dart:72:36)
I/flutter ( 4119): <asynchronous suspension>
I/flutter ( 4119): #8      SvgPicture.svgStringDecoder.<anonymous closure> (package:flutter_svg/svg.dart:531:15)
I/flutter ( 4119): #9      AssetBundlePictureProvider._loadAsync (package:flutter_svg/src/picture_provider.dart:453:12)
I/flutter ( 4119): <asynchronous suspension>
I/flutter ( 4119): #10     AssetBundlePictureProvider.load (package:flutter_svg/src/picture_provider.dart:431:43)
I/flutter ( 4119): #11     PictureProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter_svg/src/picture_provider.dart:323:17)
I/flutter ( 4119): #12     PictureCache.putIfAbsent (package:flutter_svg/src/picture_cache.dart:67:22)
I/flutter ( 4119): #13     PictureProvider.resolve.<anonymous closure> (package:flutter_svg/src/picture_provider.dart:321:16)
I/flutter ( 4119): #14     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
I/flutter ( 4119): #15     PictureProvider.resolve (package:flutter_svg/src/picture_provider.dart:318:24)
I/flutter ( 4119): #16     _SvgPictureState._resolveImage (package:flutter_svg/svg.dart:641:10)
I/flutter ( 4119): #17     _SvgPictureState.didChangeDependencies (package:flutter_svg/svg.dart:615:5)
I/flutter ( 4119): #18     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3862:12)
I/flutter ( 4119): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 4119): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 4119): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 4119): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 4119): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 4119): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 4119): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 4119): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 4119): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 4119): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 4119): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 4119): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter ( 4119): #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 4119): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 4119): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 4119): #34     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 4119): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 4119): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 4119): #37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 4119): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 4119): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 4119): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 4119): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 4119): #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter ( 4119): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 4119): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 4119): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 4119): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 4119): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 4119): #48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter ( 4119): #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 4119): #50     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4063:11)
I/flutter ( 4119): #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 4119): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 4119): #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 4119): #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 4119): #55     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter ( 4119): #56     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter ( 4119): #57     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 4119): #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 4119): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 4119): #60     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1034:36)
I/flutter ( 4119): #61     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1019:20)
I/flutter ( 4119): #62     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2258:19)
I/flutter ( 4119): #63     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1012:11)
I/flutter ( 4119): #64     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:275:23)
I/flutter ( 4119): #65     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1740:58)
I/flutter ( 4119): #66     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:797:15)
I/flutter ( 4119): #67     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1740:13)
I/flutter ( 4119): #68     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:264:5)
I/flutter ( 4119): #69     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:348:5)
I/flutter ( 4119): #70     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:78:12)
I/flutter ( 4119): #71     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #72     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter ( 4119): #73     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #74     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:407:13)
I/flutter ( 4119): #75     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1322:12)
I/flutter ( 4119): #76     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1240:20)
I/flutter ( 4119): #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #78     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #79     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #80     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #81     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #82     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #83     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #84     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #85     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #86     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #87     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #88     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #89     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #90     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #91     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #92     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #93     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #94     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #95     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #96     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:209:13)
I/flutter ( 4119): #97     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #98     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:799:17)
I/flutter ( 4119): #99     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #100    RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
I/flutter ( 4119): #101    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #102    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #103    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #104    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #105    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #106    RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:165:27)
I/flutter ( 4119): #107    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #108    RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:407:13)
I/flutter ( 4119): #109    RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1322:12)
I/flutter ( 4119): #110    RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1240:20)
I/flutter ( 4119): #111    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #112    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #113    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #114    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #115    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #116    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #117    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #118    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #119    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #120    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #121    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #122    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #123    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #124    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #125    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #126    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #127    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #128    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #129    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #130    RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
I/flutter ( 4119): #131    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #132    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter ( 4119): #133    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:431:7)
I/flutter ( 4119): #134    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter ( 4119): #135    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter ( 4119): #136    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #137    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #138    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #139    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #140    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1206:11)
I/flutter ( 4119): #141    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #142    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #143    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #144    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #145    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #146    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #147    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #148    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #149    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #150    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #151    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #152    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #153    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #154    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4119): #155    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #156    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3013:14)
I/flutter ( 4119): #157    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4119): #158    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter ( 4119): #159    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1519:7)
I/flutter ( 4119): #160    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
I/flutter ( 4119): #161    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:347:19)
I/flutter ( 4119): #162    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter ( 4119): #163    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter ( 4119): #164    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter ( 4119): #165    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter ( 4119): #166    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
I/flutter ( 4119): #170    _invoke (dart:ui/hooks.dart:219:10)
I/flutter ( 4119): #171    _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter ( 4119): (elided 3 frames from package dart:async)
I/flutter ( 4119): Picture provider: ExactAssetPicture(name: "assets/languages/python.svg", bundle: null, colorFilter:
I/flutter ( 4119): null)
I/flutter ( 4119): Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#22220(), name:
I/flutter ( 4119): "assets/languages/python.svg", colorFilter: null)
I/flutter ( 4119): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by dnfield** [comment]
Can you include `python.svg` that's causing this?

**Comment by boanergepro** [comment]
I am carrying that image and it is throwing that error.

**Comment by boanergepro** [comment]
<svg width="128" height="128" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="a" y2="78.453%" x2="79.639%" y1="11.7%" x1="12.959%"><stop offset="0%" stop-color="#387EB8"/><stop offset="100%" stop-color="#366994"/></linearGradient><linearGradient id="b" y2="88.773%" x2="90.742%" y1="20.316%" x1="19.128%"><stop offset="0%" stop-color="#FFE052"/><stop offset="100%" stop-color="#FFC331"/></linearGradient></defs><path fill="none" d="M-1-1h130v130H-1z"/><g><g stroke="null" fill-rule="evenodd" fill="none"><path fill="url(#a)" d="M63.572 4.91c-30.11 0-28.23 13.078-28.23 13.078l.035 13.55H64.11v4.068H23.963s-19.266-2.19-19.266 28.24C4.698 94.28 21.514 93.2 21.514 93.2H31.55V79.077s-.54-16.844 16.548-16.844h28.498s16.01.26 16.01-15.5V20.678s2.432-15.77-29.034-15.77zM47.73 14.02c2.858 0 5.168 2.315 5.168 5.178 0 2.864-2.31 5.178-5.17 5.178-2.857 0-5.168-2.314-5.168-5.178 0-2.863 2.31-5.177 5.17-5.177z"/><path fill="url(#b)" d="M64.428 123.09c30.11 0 28.23-13.078 28.23-13.078l-.035-13.55H63.89v-4.068h40.145s19.267 2.19 19.267-28.24c0-30.432-16.816-29.353-16.816-29.353H96.45v14.122s.54 16.844-16.55 16.844H51.405s-16.01-.26-16.01 15.5v26.056s-2.432 15.77 29.034 15.77zm15.843-9.11c-2.858 0-5.168-2.315-5.168-5.178 0-2.864 2.31-5.178 5.17-5.178 2.857 0 5.168 2.314 5.168 5.178 0 2.863-2.31 5.177-5.17 5.177z"/></g></g></svg>

**Comment by boanergepro** [comment]
<svg width="128" height="128" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="a" y2="78.453%" x2="79.639%" y1="11.7%" x1="12.959%"><stop offset="0%" stop-color="#387EB8"/><stop offset="100%" stop-color="#366994"/></linearGradient><linearGradient id="b" y2="88.773%" x2="90.742%" y1="20.316%" x1="19.128%"><stop offset="0%" stop-color="#FFE052"/><stop offset="100%" stop-color="#FFC331"/></linearGradient></defs><path fill="none" d="M-1-1h130v130H-1z"/><g><g stroke="null" fill-rule="evenodd" fill="none"><path fill="url(#a)" d="M63.572 4.91c-30.11 0-28.23 13.078-28.23 13.078l.035 13.55H64.11v4.068H23.963s-19.266-2.19-19.266 28.24C4.698 94.28 21.514 93.2 21.514 93.2H31.55V79.077s-.54-16.844 16.548-16.844h28.498s16.01.26 16.01-15.5V20.678s2.432-15.77-29.034-15.77zM47.73 14.02c2.858 0 5.168 2.315 5.168 5.178 0 2.864-2.31 5.178-5.17 5.178-2.857 0-5.168-2.314-5.168-5.178 0-2.863 2.31-5.177 5.17-5.177z"/><path fill="url(#b)" d="M64.428 123.09c30.11 0 28.23-13.078 28.23-13.078l-.035-13.55H63.89v-4.068h40.145s19.267 2.19 19.267-28.24c0-30.432-16.816-29.353-16.816-29.353H96.45v14.122s.54 16.844-16.55 16.844H51.405s-16.01-.26-16.01 15.5v26.056s-2.432 15.77 29.034 15.77zm15.843-9.11c-2.858 0-5.168-2.315-5.168-5.178 0-2.864 2.31-5.178 5.17-5.178 2.857 0 5.168 2.314 5.168 5.178 0 2.863-2.31 5.177-5.17 5.177z"/></g></g></svg>

**Comment by dnfield** [comment]
I believe your problem is with `stroke="null"`.  The literal `null` is not a valid value for SVG - did you mean to use `stroke="none"`?

**Comment by boanergepro** [comment]
Thanks, it works.

**Comment by basharkousa** [comment]
Hi @dnfield 

> I believe your problem is with `stroke="null"`. The literal `null` is not a valid value for SVG - did you mean to use `stroke="none"`?

How can I update the svg pic attributes when I'm loading it using SvgPicture.network?

**Comment by boanergepro** [comment]
> Hi @dnfield
> 
> > I believe your problem is with `stroke="null"`. The literal `null` is not a valid value for SVG - did you mean to use `stroke="none"`?
> 
> How can I update the svg pic attributes when I'm loading it using SvgPicture.network?


Hello, don't ask me, but I faced your same problem and since I couldn't modify the null value in the remote svg, I had to modify the package code, this is my change to support the null value.

https://github.com/dnfield/flutter_svg/compare/master...boanergepro:master
