### ISSUE TITLE
Exception thrown when using with {headers : ...}

### ISSUE THREAD

**Issue by lifenautjoe** [dnfield/flutter_svg#226]
Hi Dan,

First off, thanks for the great library!

Here's an issue I'm facing giving it a go which I hope when resolved, will help improve it.

When using the network option with headers

```
SvgPicture.network(
        imageSource,
        headers: {'Authorization': 'Token $proxyAuthToken'} ,
        semanticsLabel: semanticsLabel,
        fit: BoxFit.cover,
        placeholderBuilder: (BuildContext context) =>
            Image.asset('assets/images/fallbacks/post-fallback.png'),
      );
```

The following exception is thrown

```
flutter: ══╡ EXCEPTION CAUGHT BY SVG ╞═══════════════════════════════════════════════════════════════════════
flutter: The following HttpException was thrown resolving a single-frame picture stream:
flutter: Could not get network asset, uri =
flutter: https://contentproxy.okuna.io:80/?https://nu.nl/static/img/atoms/images/logos/nu_logo.svg
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      httpGet (package:flutter_svg/src/utilities/http.dart:20:5)
flutter: <asynchronous suspension>
flutter: #1      NetworkPicture._loadAsync (package:flutter_svg/src/picture_provider.dart:503:35)
flutter: <asynchronous suspension>
flutter: #2      NetworkPicture.load (package:flutter_svg/src/picture_provider.dart:493:43)
flutter: #3      PictureProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter_svg/src/picture_provider.dart:323:17)
flutter: #4      PictureCache.putIfAbsent (package:flutter_svg/src/picture_cache.dart:67:22)
flutter: #5      PictureProvider.resolve.<anonymous closure> (package:flutter_svg/src/picture_provider.dart:321:16)
flutter: #6      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
flutter: #7      PictureProvider.resolve (package:flutter_svg/src/picture_provider.dart:318:24)
flutter: #8      _SvgPictureState._resolveImage (package:flutter_svg/svg.dart:641:10)
flutter: #9      _SvgPictureState.didChangeDependencies (package:flutter_svg/svg.dart:615:5)
flutter: #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4086:12)
flutter: #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #27     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4314:11)
flutter: #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #29     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5233:32)
flutter: #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #44     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #50     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
flutter: #51     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #56     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #57     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #60     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #64     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #65     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #66     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #69     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4910:32)
flutter: #70     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5243:17)
flutter: #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
flutter: #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #73     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #74     StatefulElement.update (package:flutter/src/widgets/framework.dart:4120:5)
flutter: #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
flutter: #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #77     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #78     ProxyElement.update (package:flutter/src/widgets/framework.dart:4254:5)
flutter: #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
flutter: #80     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4852:32)
flutter: #81     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5243:17)
flutter: #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
flutter: #83     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
flutter: #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
flutter: #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #87     StatelessElement.update (package:flutter/src/widgets/framework.dart:4016:5)
flutter: #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
flutter: #89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #90     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #91     StatefulElement.update (package:flutter/src/widgets/framework.dart:4120:5)
flutter: #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
flutter: #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #94     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #95     StatelessElement.update (package:flutter/src/widgets/framework.dart:4016:5)
flutter: #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
flutter: #97     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
flutter: #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
flutter: #99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #100    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #101    StatefulElement.update (package:flutter/src/widgets/framework.dart:4120:5)
flutter: #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
flutter: #103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #104    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #105    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2348:33)
flutter: #106    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:760:20)
flutter: #107    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280:5)
flutter: #108    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
flutter: #109    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
flutter: #110    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891:5)
flutter: #114    _invoke (dart:ui/hooks.dart:249:10)
flutter: #115    _drawFrame (dart:ui/hooks.dart:207:3)
flutter: (elided 3 frames from package dart:async)
flutter:
flutter: Picture provider:
flutter:   NetworkPicture("https://contentproxy.okuna.io:80/?https://nu.nl/static/img/atoms/images/logos/nu_logo.svg",
flutter:   headers: {Authorization: Token xxxx}, colorFilter: null)
flutter: Picture key:
flutter:   NetworkPicture("https://contentproxy.okuna.io:80/?https://nu.nl/static/img/atoms/images/logos/nu_logo.svg",
flutter:   headers: {Authorization: Token xxxx}, colorFilter: null)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

When using without the headers option, works as expected.

### Flutter doctor

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G84, locale en-NL)
    • Flutter version 1.9.1+hotfix.2 at /Users/lifenautjoe/Documents/code/libraries/flutter
    • Framework revision 2d2a1ffec9 (11 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/lifenautjoe/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 33.3.2
    • Dart plugin version 183.5912.23

[✓] Connected device (1 available)
    • 🥑 • 1d548d079169fde4d329284ea2448a5b8982eaf3 • ios • iOS 12.4.1

• No issues found!
```

As a side question, are there some extra headers appended to the request apart from the provided ones?

**Comment by dnfield** [comment]
Can you try reproducing this with just a simple HTTP request using those headers?

I suspect this isnt' an issue with the SVG package specifically...

**Comment by dnfield** [comment]
Without further information I'm not sure what to do with this bug. If you have anything to add please feel free to comment and I'll reopen.
