### ISSUE TITLE
build errors with Flutter run 

### ISSUE THREAD

**Issue by Stivfk** [dnfield/flutter_svg#246]
When i tried to do `Flutter run --verbose` i get the following error:

> [ +309 ms] [DEVICE LOG] 2019-11-12 14:32:28.533462+0400  localhost Runner[55784]: (Flutter) [VERBOSE-2:FontFamily.cpp(184)] Could not get cmap
table size!
> [   +1 ms] [DEVICE LOG] 2019-11-12 14:32:28.533608+0400  localhost Runner[55784]: (Flutter) [VERBOSE-3:FontCollection.cpp(95)] nTypefaces == 0
> [        ] [VERBOSE-2:FontFamily.cpp(184)] Could not get cmap table size!
> [        ] [VERBOSE-3:FontCollection.cpp(95)] nTypefaces == 0
> [   +4 ms] Service protocol connection closed.
> [   +1 ms] Lost connection to device.

```
#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:477:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:522:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#12     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#20     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#27     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

```
i have Flutter v1.9.1+hotfix.4

Anyone have any idea what's going on?

**Comment by dnfield** [comment]
What version of Android?

**Comment by dnfield** [comment]
This is almost certainly not a bug for this repo, and has no responses here.  It's quite possible you have an upstream bug in Flutter or Skia affecting this.
