### ISSUE TITLE
Custom color is not set in tests

### ISSUE THREAD

**Issue by vanlooverenkoen** [dnfield/flutter_svg#300]
I have created a custom widget that can be used for an svg icon. Everything works perfectly when using it in a flutter app. But when using it in tests a custom color is not shown in the golden files. 

```
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

class SvgIcon extends StatelessWidget {
  final String svgAsset;
  final Color color;
  final double size;

  const SvgIcon({
    @required this.svgAsset,
    this.color = Colors.black,
    this.size,
  });

  @override
  Widget build(BuildContext context) {
    return SvgPicture.asset(
      svgAsset,
      height: size,
      width: size,
      color: color,
    );
  }
}
```

My tests:

```
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import '../di/test_kiwi_util.dart';
import '../util/test_util.dart';

void main() {
  testWidgets('SvgIcon initial state', (tester) async {
    const sut = SvgIcon(svgAsset: 'assets/images/icons/android/map.svg');


    final testWidget = TestWrapper(child: sut);
    tester.allWidgets.toList().clear();
    await tester.pumpWidget(testWidget);
    await tester.pumpAndSettle();
    await takeScreenshot(tester, 'svg_icon_initial_state');
  });

  testWidgets('SvgIcon custom color', (tester) async {
    const sut = SvgIcon(
      svgAsset: 'assets/images/icons/android/map.svg',
      color: Colors.purple,
    );

    final testWidget = TestWrapper(child: sut);
    tester.allWidgets.toList().clear();
    await tester.pumpWidget(testWidget);
    await tester.pumpAndSettle();
    await takeScreenshot(tester, 'svg_icon_custom_color');
  });

  testWidgets('SvgIcon custom size', (tester) async {
    const sut = SvgIcon(
      svgAsset: 'assets/images/icons/android/map.svg',
      size: ThemeDimens.padding64,
    );

    final testWidget = TestWrapper(child: sut);
    tester.allWidgets.toList().clear();
    await tester.pumpWidget(testWidget);
    await tester.pumpAndSettle();
    await takeScreenshot(tester, 'svg_icon_custom_size');
  });

  testWidgets('SvgIcon custom size and color', (tester) async {
    const sut = SvgIcon(
      svgAsset: 'assets/images/icons/android/map.svg',
      color: Colors.purple,
      size: ThemeDimens.padding64,
    );

    final testWidget = TestWrapper(child: sut);
    tester.allWidgets.toList().clear();
    await tester.pumpWidget(testWidget);
    await tester.pumpAndSettle();
    await takeScreenshot(tester, 'svg_icon_custom_size_and_color');
  });
}

Future<void> takeScreenshot(WidgetTester tester, String snapshotName) async {
  expect(find.byType(TestWrapper), findsOneWidget);
  await expectLater(
    find.byType(TestWrapper),
    matchesGoldenFile('img/$snapshotName.png'),
  );
}


class TestWrapper extends StatelessWidget {
  final Widget child;

  const TestWrapper({@required this.child});

  @override
  Widget build(BuildContext context) {
    return RepaintBoundary(
      child: child,
    );
  }
}

```
svg_icon_initial_state
![svg_icon_initial_state](https://user-images.githubusercontent.com/21172855/75424180-6e357e80-5940-11ea-81d9-56818f20aa28.png)
svg_icon_custom_color
![svg_icon_custom_color](https://user-images.githubusercontent.com/21172855/75424173-6c6bbb00-5940-11ea-85dc-757003e02f7a.png)
svg_icon_custom_size
![svg_icon_custom_size](https://user-images.githubusercontent.com/21172855/75424174-6d045180-5940-11ea-899e-e72ee83621c2.png)
svg_icon_custom_size_and_color
![svg_icon_custom_size_and_color](https://user-images.githubusercontent.com/21172855/75424177-6e357e80-5940-11ea-93c7-fd582b0f6191.png)

**Comment by dnfield** [comment]
Can you share a version of your test that I can paste into a test file and run? E.g. using `SvgPicture.string` instead of `asset`, and having the defined class you're using in the test file?

**Comment by dnfield** [comment]
I suspect there's something strange going on with FakeAsync here.

**Comment by vanlooverenkoen** [comment]
This is the svg
```
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
    <path fill="#fff" d="M15 18.984V7.125l-6-2.11v11.86l6 2.11zM20.484 3c.344 0 .516.172.516.516v15.093c0 .25-.125.407-.375.47L15 21l-6-2.11-5.344 2.063-.14.047C3.172 21 3 20.828 3 20.484V5.391c0-.25.125-.407.375-.47L9 3l6 2.11 5.344-2.063.14-.047z"/>
</svg>
```

**Comment by dnfield** [comment]
Thanks

**Comment by vanlooverenkoen** [comment]
We also have written tests where we go through the complete app. And then we can see that the icons are rendered correctly. Also in development or release we see that the svg picture is rendered with the correct color. only in tests and when we run this code we have this problem very strange

**Comment by dnfield** [comment]
What are you trying to do with `tester.allWidgets.toList().clear();`?  that code doesn't actually do anything meaningful :)  

The following simplified test appears to work fine for me:

```dart
  testWidgets('new', (tester) async {
    final GlobalKey key = GlobalKey();
    await tester.pumpWidget(
      RepaintBoundary(
        key: key,
        child: Container(
          color: const Color(0xFFABCDEF),
          child: SvgPicture.string(
            '''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
    <path fill="#fff" d="M15 18.984V7.125l-6-2.11v11.86l6 2.11zM20.484 3c.344 0 .516.172.516.516v15.093c0 .25-.125.407-.375.47L15 21l-6-2.11-5.344 2.063-.14.047C3.172 21 3 20.828 3 20.484V5.391c0-.25.125-.407.375-.47L9 3l6 2.11 5.344-2.063.14-.047z"/>
</svg>''',
            color: const Color(0xFFFEDCBA),
          ),
        ),
      ),
    );
    await tester.pumpAndSettle();
    await expectLater(
      find.byKey(key),
      matchesGoldenFile('test.png'),
    );
  });
```

**Comment by vanlooverenkoen** [comment]
Oke sure the test.allWidgets.toList().clear(); was something I tried but can be removed indeed.

I tried your code and it is working fine indeed. but why isn't this code working?

```
import 'package:flutter/material.dart';
import 'package:flutter_svg/svg.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('new', (tester) async {
    final GlobalKey key = GlobalKey();
    await tester.pumpWidget(
      RepaintBoundary(
        key: key,
        child: Icon(color: Colors.blue),
      ),
    );
    await tester.pumpAndSettle();
    await expectLater(
      find.byKey(key),
      matchesGoldenFile('test.png'),
    );
  });
  testWidgets('new 2', (tester) async {
    final GlobalKey key = GlobalKey();
    await tester.pumpWidget(
      RepaintBoundary(
        key: key,
        child: Icon(color: Colors.orange),
      ),
    );
    await tester.pumpAndSettle();
    await expectLater(
      find.byKey(key),
      matchesGoldenFile('test2.png'),
    );
  });
}

class Icon extends StatelessWidget {
  final Color color;
  final double size;

  const Icon({
    this.color = Colors.grey,
    this.size,
  });

  @override
  Widget build(BuildContext context) {
    return Center(
      child: SvgPicture.asset(
        'assets/images/icons/android/map.svg',
        color: color,
        height: size,
        width: size,
      ),
    );
  }
}
```

With the SvgPicture.string it is working fine. but I do not want to be using the asset function

**Comment by dnfield** [comment]
Ah! hah.

For an asset, you have to load it in a `tester.runAsync` zone.  You also have to make sure you don't end up with it being cached from the FakeAsync zone, because it's not going to complete properly in that case.

I'm fairly certain that's what it is at this point :)

**Comment by vanlooverenkoen** [comment]
Ah oke I did not know that. How can I prevent it from being cached?

**Comment by dnfield** [comment]
I believe something like this should work:

```dart
  await tester.runAsync(() async {
    PictureProvider.clearCache();
    final GlobalKey key = GlobalKey();
    await tester.pumpWidget(
      RepaintBoundary(
        key: key,
        child: Icon(color: Colors.orange),
      ),
    );
    await tester.pumpAndSettle();
    await expectLater(
      find.byKey(key),
      matchesGoldenFile('test2.png'),
    );
  });
```

**Comment by vanlooverenkoen** [comment]
And how would my test then look? 
```
  testWidgets('new 2', (tester) async {
    await tester.runAsync(() async {
      final GlobalKey key = GlobalKey();
      await tester.pumpWidget(
        RepaintBoundary(
          key: key,
          child: Icon(color: Colors.orange),
        ),
      );
      await tester.pumpAndSettle();
      await expectLater(
        find.byKey(key),
        matchesGoldenFile('test2.png'),
      );
    });
  });
```

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown while running async test code:
  Reentrant call to runAsync() denied.
runAsync() was called, then before its future completed, it was called again. You must wait for the
first returned future to complete before calling runAsync() again.

When the exception was thrown, this was the stack:
#0      AutomatedTestWidgetsFlutterBinding.runAsync.<anonymous closure> (package:flutter_test/src/binding.dart:888:7)
#1      AutomatedTestWidgetsFlutterBinding.runAsync (package:flutter_test/src/binding.dart:894:6)
#2      _MatchesGoldenFile.matchAsync (package:flutter_test/src/matchers.dart:1744:20)
#4      _MatchesGoldenFile.matchAsync (package:flutter_test/src/matchers.dart:1724:28)
#5      _expect (package:test_api/src/frontend/expect.dart:116:26)
#6      expectLater (package:test_api/src/frontend/expect.dart:75:5)
#7      expectLater (package:flutter_test/src/widget_tester.dart:271:10)
#8      main.<anonymous closure>.<anonymous closure> (file:///Users/vanlooverenkoen/Documents/work/flutter_sibos/test/test.dart:30:13)
(elided 14 frames from package dart:async, package dart:async-patch, and package stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by dnfield** [comment]
Argh.  Yeah.  We don't make this easy at all.  It's going to be really hard to unit test this - there's no simple solution to it, and anything you do for this will make your tests potentially flaky.  The easiest solution is to just do integration tests for this unfortunately.  You could also try to use the live test binding.

**Comment by vanlooverenkoen** [comment]
But why does it work for the first test but not for the second? that is something I do not get?

**Comment by vanlooverenkoen** [comment]
And if I do this:
```
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:flutter_svg/svg.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('new', (tester) async {
    final GlobalKey key = GlobalKey();
    await tester.pumpWidget(
      RepaintBoundary(
        key: key,
        child: Icon(color: Colors.blue),
      ),
    );
    await tester.pumpAndSettle();
    await expectLater(
      find.byKey(key),
      matchesGoldenFile('test.png'),
    );
  });
  testWidgets('new 2', (tester) async {
    final GlobalKey key = GlobalKey();
    await tester.pumpWidget(
      RepaintBoundary(
        key: key,
        child: Icon(color: Colors.orange),
      ),
    );
    await tester.pumpAndSettle();
    await expectLater(
      find.byKey(key),
      matchesGoldenFile('test2.png'),
    );
  });
}

class Icon extends StatelessWidget {
  final Color color;

  const Icon({
    this.color = Colors.grey,
  });

  @override
  Widget build(BuildContext context) {
    return SvgPicture.asset(
      'assets/images/icons/android/map.svg',
      color: Colors.black,
    );
  }
}
```

both tests are successfull.

**Comment by vanlooverenkoen** [comment]
This is what I use at the moment.

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_svg/flutter_svg.dart';

class SvgIcon extends StatelessWidget {
  final String svgAsset;
  final Color color;
  final double size;

  const SvgIcon({
    @required this.svgAsset,
    this.color = Colors.black,
    this.size,
  });

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<String>(
      future: _getSvgString(),
      builder: (context, snapshot) {
        if (snapshot.hasData) {
          return SvgPicture.string(
            snapshot.data,
            height: size,
            width: size,
            color: color,
          );
        }
        return Container(
          height: size,
          width: size,
        );
      },
    );
  }

  Future<String> _getSvgString() async {
    return rootBundle.loadString(svgAsset);
  }
}
```
