### ISSUE TITLE
Basic SVG Text to PNG fails with `Cannot provide both a color and a foreground`

### ISSUE THREAD

**Issue by Grooviz** [dnfield/flutter_svg#463]
## Use case:

We want to download a PNG version of an SVG such as:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 200 200" stroke="none">
  <text x="50" y="50" style="fill: red;">I love SVG!</text>
</svg>
```

## What should happen?

The PNG should be created and downloaded.

## What happened?

The PNG File creation fails with the following error:

```
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/text/paragraph.dart:949:13
color == null || foreground == null
"Cannot provide both a color and a foreground\nThe color argument is just a shorthand for \"foreground: new Paint()..color = color\"."
    at Object.throw_ [as throw] (http://localhost:54521/dart_sdk.js:4348:11)
    at Object.assertFailed (http://localhost:54521/dart_sdk.js:4291:15)
    at new _engine.EngineTextStyle.only (http://localhost:54521/dart_sdk.js:169542:54)
    at _engine.DomParagraphBuilder.new.[_tryBuildPlainText] (http://localhost:54521/dart_sdk.js:169772:29)
    at _engine.DomParagraphBuilder.new.build (http://localhost:54521/dart_sdk.js:169686:38)
    at Object.createParagraph (http://localhost:54521/packages/flutter_svg/src/svg/xml_parsers.dart.lib.js:746:19)
    at _processText (http://localhost:54521/packages/flutter_svg/src/svg/parser_state.dart.lib.js:438:30)
    at text (http://localhost:54521/packages/flutter_svg/src/svg/parser_state.dart.lib.js:470:13)
    at text.next (<anonymous>)
    at runBody (http://localhost:54521/dart_sdk.js:37976:34)
    at Object._async [as async] (http://localhost:54521/dart_sdk.js:38007:7)
    at text (http://localhost:54521/packages/flutter_svg/src/svg/parser_state.dart.lib.js:423:20)
    at parser_state.SvgParserState.new.parse (http://localhost:54521/packages/flutter_svg/src/svg/parser_state.dart.lib.js:667:56)
    at parse.next (<anonymous>)
    at http://localhost:54521/dart_sdk.js:37956:33
    at _RootZone.runUnary (http://localhost:54521/dart_sdk.js:37810:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:54521/dart_sdk.js:32771:29)
    at handleValueCallback (http://localhost:54521/dart_sdk.js:33319:49)
    at Function._propagateToListeners (http://localhost:54521/dart_sdk.js:33357:17)
    at async._AsyncCallbackEntry.new.callback (http://localhost:54521/dart_sdk.js:33082:27)
    at Object._microtaskLoop (http://localhost:54521/dart_sdk.js:38071:13)
    at _startMicrotaskLoop (http://localhost:54521/dart_sdk.js:38077:13)
    at http://localhost:54521/dart_sdk.js:33574:9
```

## How to reproduce?

```
import 'dart:typed_data';
import 'dart:ui' as ui;
import 'dart:html' as html;

import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Center(
          child: ElevatedButton(
            onPressed: () {
              svgToPng(svgSample).then((ByteData data) {
                downloadBytes(
                  data.buffer
                      .asUint8List(data.offsetInBytes, data.lengthInBytes),
                  'png',
                );
              });
            },
            child: const Text('Download PNG'),
          ),
        ),
      ),
    );
  }
}

const String svgSample = '''<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 200 200" stroke="none">
  <text x="50" y="50" style="fill: red;">I love SVG!</text>
</svg>
''';

Future<ByteData> svgToPng(String rawSvg) async {
  final DrawableRoot svgRoot = await svg.fromSvgString(rawSvg, rawSvg);
  final ui.Picture picture = svgRoot.toPicture(
    size: const Size(1000, 1000),
    clipToViewBox: true,
  );
  final ui.Image image = await picture.toImage(1000, 1000);
  final ByteData data = await image.toByteData(format: ui.ImageByteFormat.png);
  return data;
}

void downloadBytes(Uint8List bytes, String ext) {
  final List<Uint8List> data = [bytes];
  final html.Blob blob = html.Blob(data);
  final String url = html.Url.createObjectUrlFromBlob(blob);
  final html.Element anchor =
      html.document.createElement('a') as html.AnchorElement
        ..href = url
        ..style.display = 'none'
        ..download = 'qr.$ext';
  html.document.body.children.add(anchor);
  anchor.click();
  html.document.body.children.remove(anchor);
  html.Url.revokeObjectUrl(url);
}
```

**Comment by Grooviz** [comment]
## Preliminary analysis of the problem.

The Assertion Failure is caused by `createParagraph`:

```
/// Creates a [Paragraph] object using the specified [text], [style], and
/// [foregroundOverride].
Paragraph createParagraph(
  String text,
  DrawableStyle style,
  DrawablePaint? foregroundOverride,
) {
  final ParagraphBuilder builder = ParagraphBuilder(ParagraphStyle())
    ..pushStyle(
      style.textStyle!.toFlutterTextStyle(
        foregroundOverride: foregroundOverride,
      ),
    )
    ..addText(text);
  return builder.build()..layout(_infiniteParagraphConstraints);
}
```

`foregroundOverride` should probably not be used if `style` defines a `fill` property.

I could bypass the problem with:

```
...
      style.textStyle!.toFlutterTextStyle(
        foregroundOverride: style.fill == null ? foregroundOverride : null,
      ),
...
```

Not sure it's the best way to fix this, though.

**Comment by dnfield** [comment]
I _think_ this might actually be a bug in the web engine code rather than flutter_svg.

For example, this same SVG renders as expected with no error on VM based Flutter, and the SVG code is not setting both `color` and `foreground`.

See `_tryBuildPlainText`, where `color` is defaulted to a non-null value.

**Comment by dnfield** [comment]
Yup.

Minimal reproduction:

```dart
import 'dart:ui';

void main() {
  final ParagraphBuilder builder = ParagraphBuilder(ParagraphStyle());
  builder.pushStyle(TextStyle(foreground: Paint()..color = const Color(0xFFABCDEF)));
  builder.addText('hi');
  final Paragraph paragraph = builder.build();
  print(paragraph);
}
```

Will file an upstream bug for this.

**Comment by dnfield** [comment]
Closing this in favor of the upstream bug in Flutter repo.
