### ISSUE TITLE
Error to open svg: Invalid double 100%

### ISSUE THREAD

**Issue by Ron-Junior** [dnfield/flutter_svg#559]
So when opening this link [https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/cartola_svg_185/escudo/01/33/58/0085562bf0-96a3-4227-9d76-8c46fd9ccc0120210502223358](url)

We have this error:  Invalid double 100%

So the problem here is that the function parseDouble on "svg/parser_state.dart" only removes the px string to the "maybeDouble" variable. So.. in my humble opinion the solutions is 
` maybeDouble = maybeDouble.trim().replaceFirst(RegExp(r'(px|%)'), '').trim();` 
I will open a pr to this. if this is a good solution you cans approve it

The stack trace below:
When the exception was thrown, this was the stack
#0      double.parse (dart:core-patch/double_patch.dart:111:28)
#1      parseDouble    package:flutter_svg/…/utilities/numbers.dart:15
#2      _Paths.rect      package:flutter_svg/…/svg/parser_state.dart:655
#3      SvgParserState.addShape package:flutter_svg/…/svg/parser_state.dart:874
#4      SvgParserState.startElement package:flutter_svg/…/svg/parser_state.dart:902

**Comment by kimmanwky** [comment]
anyone fixed this issue? i have the same problem. It is still not working on v0.22.0.

**Comment by ZaifSenpai** [comment]
Same issue occurred while trying to show [this SVG](https://api.dicebear.com/5.x/initials/svg?seed=nfc921FkibWpTQtVCMcMfTwwNL2fx74IU3oyQCnpErVR77sFgeU0Wl9a422CwCJmwhD7ZJSvr7ETVl9NZC0JIWPrVqE2Fos15Uscl3AmDX60y2bIB6Og2zCrH302ND&radius=0&scale=100&flip=false&rotate=0&translateX=0&translateY=0)

**Comment by pansitwattana** [comment]
Hello, I also got this error. How to fix this bugs? 
P.S. I can't modify image I download from network.

**Comment by pansitwattana** [comment]
I got solution here. I don't know if this is the best solution.

using this library: https://pub.dev/packages/flutter_inappwebview
```
 InAppWebView(
  initialUrlRequest: URLRequest(
    url: Uri.dataFromString(
      '''<svg width="100%" height="100%">       
            <image xlink:href="$qrCodeSvgUrl" width="100%" height="100%"/>    
        </svg>''',
      mimeType: 'text/html',
      encoding: Encoding.getByName('utf-8'),
    ),
  ),
),
```

**Comment by gerken-tss** [comment]
@pansitwattana 
Your solution works, not bad! The only drawback is that all the caching capabilities and other things like placeholder widgets that are part of the `flutter_svg` package are not directly available like this. As a temporary workaround, it's fine though, I guess.

**Comment by ynsmrkrds** [comment]
Hello. Is there a new solution?

**Comment by YashIngole** [comment]
any solution yet?

**Comment by angelru** [comment]
any solution?? Invalid double

**Comment by JuKu** [comment]
Same problem here.
Maybe flutter_svg is incompatible with any SVGs which use the "fill" command?

**Comment by Judimax** [comment]
I think the fix is simple grab the width and the height of the svg grab the percentage value and work with it that way?

**Comment by Jyoshnarani** [comment]
[2.0.10](https://pub.dev/packages/flutter_svg/versions/2.0.10)

latest version has same error 

 Unhandled Exception: FormatException: Invalid double
 100%

**Comment by deminearchiver** [comment]
I really want this fixed too!

**Comment by WingCH** [comment]
same issue

**Comment by JuKu** [comment]
@dnfield Can you provide a solution for this problem, please?

**Comment by Fabccc** [comment]
I'm trying to display a QRCode.
It contains a rect and a path parameter.
Having a line that contains a `rect` with `width`, `height` and `fill` properties does not works. (both width & height are at 100%)
By removing this line it works fine.
Even if my path tag has a fill, it does works.
