### ISSUE TITLE
Svg didn't render

### ISSUE THREAD

**Issue by domestia** [dnfield/flutter_svg#683]
Hi, I'm using 'SvgPicture.asset(myAsset, color: myColor)' for a while without problem but I can't figure out why my new svg can't render :/ 

`======== Exception caught by SVG ===================================================================
The following assertion was thrown resolving a single-frame picture stream:
Unable to load asset: plan_zone.svg

When the exception was thrown, this was the stack: 
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:237:7)
<asynchronous suspension>
#1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:72:27)
<asynchronous suspension>
#2      AssetBundlePictureProvider._loadAsync (package:flutter_svg/src/picture_provider.dart:546:25)
<asynchronous suspension>
Picture provider: ExactAssetPicture(name: "plan_zone.svg", bundle: null, colorFilter: null)
Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#9f7ec(), name: "plan_zone.svg", colorFilter: null, theme: SvgTheme(currentColor: null, fontSize: 18.0, xHeight: 9.0))`

I think the problem come from an element in my file so I try without style but it's the same.
svg is attach.
![plan_zone](https://user-images.githubusercontent.com/90703487/158792754-f8f46712-78f7-43c3-af32-406d786f4334.svg)

thanks.

**Comment by domestia** [comment]
sry, wrong typo... -_-
