### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by sonofnos** [dnfield/flutter_svg#751]
I am getting this error on my console 

```
I/flutter (15529): ══╡ EXCEPTION CAUGHT BY SVG ╞═══════════════════════════════════════════════════════════════════════
I/flutter (15529): The following _CastError was thrown resolving a single-frame picture stream:
I/flutter (15529): Null check operator used on a null value
I/flutter (15529): 
I/flutter (15529): When the exception was thrown, this was the stack:
I/flutter (15529): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:235:39)
I/flutter (15529): #1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:72:33)
I/flutter (15529): #2      CachingAssetBundle.loadString.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:172:56)
I/flutter (15529): #3      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:484:23)
I/flutter (15529): #4      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:172:27)
I/flutter (15529): #5      AssetBundlePictureProvider._loadAsync (package:flutter_svg/src/picture_provider.dart:546:42)
I/flutter (15529): #6      AssetBundlePictureProvider.load (package:flutter_svg/src/picture_provider.dart:531:7)
I/flutter (15529): #7      PictureProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter_svg/src/picture_provider.dart:378:19)
I/flutter (15529): #8      PictureCache.putIfAbsent (package:flutter_svg/src/picture_cache.dart:91:22)
I/flutter (15529): #9      PictureProvider.resolve.<anonymous closure> (package:flutter_svg/src/picture_provider.dart:376:17)
I/flutter (15529): #10     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:41:35)
I/flutter (15529): #11     PictureProvider.resolve (package:flutter_svg/src/picture_provider.dart:372:24)
I/flutter (15529): #12     precachePicture (package:flutter_svg/svg.dart:198:21)
I/flutter (15529): #13     main (package:golf_app/main.dart:19:9)
I/flutter (15529): #14     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:130:25)
I/flutter (15529): #19     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:126:5)
I/flutter (15529): #20     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
I/flutter (15529): (elided 5 frames from class _RawReceivePortImpl and dart:async)
I/flutter (15529): 
I/flutter (15529): Picture provider: ExactAssetPicture(name: "assets/images/New Logo.svg", bundle: null,
I/flutter (15529):   colorFilter: null)
I/flutter (15529): Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#6712f(), name: "assets/images/New
I/flutter (15529):   Polaris Logo.svg", colorFilter: null, theme: SvgTheme(currentColor: null, fontSize: 14.0, xHeight:
I/flutter (15529):   7.0))
I/flutter (15529): ════════════════════════════════════════════════════════════════════════════════════════════════════
D/ZrHung.AppEyeUiProbe(15529): stop checker.
D/ZrHung.AppEyeUiProbe(15529): Current Activity:false
D/ZrHung.AppEyeUiProbe(15529): not watching, wait.
I/ViewRootImpl(15529): jank_removeInvalidNode all the node in jank list is out of time
I/ViewRootImpl(15529): jank_removeInvalidNode all the node in jank list is out of time
W/InputMethodManager(15529): startInputReason = 1
D/ZrHung.AppEyeUiProbe(15529): notify runnable to start.
D/ZrHung.AppEyeUiProbe(15529): restart watching
```

I am using v 1.0.3 as updating to v1.1.3/4 + dart sdk will slow the project. 

I want the svg reloaded and added this to main.dart: 

```
Future<void> main() async {
  await precachePicture(
      ExactAssetPicture(
          SvgPicture.svgStringDecoderOutsideViewBoxBuilder, 'assets/images/New Logo.svg'),
      null);
  runApp(MyApp());
}
```

**Comment by dnfield** [comment]
You're missing a `WidgetsFlutterBinding.ensureInitialized()` in your `main` method, which must be called before accessing assets.

FWIW, newer versions of Flutter give a much better error message in this case.
