### ISSUE TITLE
Bad UTF-8 encoding eception

### ISSUE THREAD

**Issue by escamoteur** [dnfield/flutter_svg#80]
I have some SVGs from our designer that throw this exception. I can open them with InkScape without problems. SVGCleaner does not process them too.
Please have a look at it. I attach one of the SVGs

```
D/EGL_emulation(11227): eglMakeCurrent: 0x7e46575f2a60: ver 3 0 (tinfo 0x7e465a08a820)
I/flutter (11227): ══╡ EXCEPTION CAUGHT BY SVG ╞═══════════════════════════════════════════════════════════════════════
I/flutter (11227): The following FormatException was thrown resolving a single-frame picture stream:
I/flutter (11227): Bad UTF-8 encoding 0xff (at offset 1335)
I/flutter (11227):
I/flutter (11227): When the exception was thrown, this was the stack:
I/flutter (11227): #0      _Utf8Decoder.convert (dart:convert/utf.dart:568:13)
I/flutter (11227): #1      Utf8Decoder.convert (dart:convert/utf.dart:344:13)
I/flutter (11227): #2      Utf8Codec.decode (dart:convert/utf.dart:66:60)
I/flutter (11227): #3      Svg.fromSvgBytes (package:flutter_svg/svg.dart:83:31)
I/flutter (11227): <asynchronous suspension>
I/flutter (11227): #4      Svg.svgPictureDecoder (package:flutter_svg/svg.dart:47:40)
I/flutter (11227): <asynchronous suspension>
I/flutter (11227): #5      SvgPicture.svgByteDecoder.<anonymous closure> (package:flutter_svg/svg.dart:446:15)
I/flutter (11227): #6      AssetBundlePictureProvider._loadAsync (package:flutter_svg/src/picture_provider.dart:424:18)
I/flutter (11227): <asynchronous suspension>
I/flutter (11227): #7      AssetBundlePictureProvider.load (package:flutter_svg/src/picture_provider.dart:406:47)
I/flutter (11227): #8      PictureProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter_svg/src/picture_provider.dart:306:57)
I/flutter (11227): #9      PictureCache.putIfAbsent (package:flutter_svg/src/picture_cache.dart:66:22)
I/flutter (11227): #10     PictureProvider.resolve.<anonymous closure> (package:flutter_svg/src/picture_provider.dart:306:34)
I/flutter (11227): #11     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
I/flutter (11227): #12     PictureProvider.resolve (package:flutter_svg/src/picture_provider.dart:304:17)
```

[icon_marker.zip](https://github.com/dnfield/flutter_svg/files/2572773/icon_marker.zip)

**Comment by dnfield** [comment]
This file does open in inkscape, but both Chrome and Safari complain about encoding errors as well.

I opened it in a text editor and removed the `<?xpacket?>` section, and it worked fine - seems like some character in or around that section got encoded improperly.  I guess Inkscape is just more tolerant of UTF8 encoding errors, but I'm not sure how I would be able to do that in Dart (or if it would even be safe).

**Comment by escamoteur** [comment]
Ok, thanks a lot now I know what the problem is
