### ISSUE TITLE
GIF asset is being detected as SVG

### ISSUE THREAD

**Issue by webhaikal** [dnfield/flutter_svg#802]
Gotten a weird error lately, a GIF asset is being detected as an SVG is throwing out errors like below.

```
======== Exception caught by SVG ===================================================================
The following FormatException was thrown resolving a single-frame picture stream:
Unexpected extension byte (at offset 8)

When the exception was thrown, this was the stack: 
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1755:7)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
#2      Utf8Codec.decode (dart:convert/utf.dart:63:20)
#3      AssetBundle._utf8decode (package:flutter/src/services/asset_bundle.dart:98:17)
#4      _IsolateConfiguration.applyAndTime.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:108:21)
#5      Timeline.timeSync (dart:developer/timeline.dart:160:22)
#6      _IsolateConfiguration.applyAndTime (package:flutter/src/foundation/_isolates_io.dart:106:21)
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:127:67)
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:17)
(elided one frame from class _RawReceivePortImpl)
Picture provider: ExactAssetPicture(name: "assets/cereka-loading.gif", bundle: null, colorFilter: null)
Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#64568(), name: "assets/cereka-loading.gif", colorFilter: null, theme: SvgTheme(currentColor: Color(0xff000000), fontSize: 14.0, xHeight: 7.0))
```

I'm not sure what is happening as the only call to the asset is through Flutter's own`Image.asset` widget. I do however have other SVG assets defined in my pubspec.

Additional details:
```
flutter_svg: 1.1.6,
flutter: 3.3.6
Framework revision 6928314d50 (2 weeks ago), 2022-10-25 16:34:41 -0400
Engine revision 3ad69d7be3
Dart version 2.18.2
```

**Comment by dnfield** [comment]
This likely means you're passing a gif somewhere to SvgPicture.

Without a reproduction I'm not sure how to help. I'd grep your codebase for assets/cereka-loading.gif and figure out where it's getting used.
