### ISSUE TITLE
Error: Unhandled Exception: FormatException: Invalid double

### ISSUE THREAD

**Issue by blue492** [dnfield/flutter_svg#843]
Hi, 
After upgrading flutter_svg to : ^2.0.0+1, I get the following error every time I run my app.
Flutter: 3.7.1

```
E/flutter ( 6485): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Invalid double
E/flutter ( 6485): 360deg
E/flutter ( 6485): #0      double.parse (dart:core-patch/double_patch.dart:112:28)
E/flutter ( 6485): #1      parseDouble (package:vector_graphics_compiler/src/svg/numbers.dart:32:17)
E/flutter ( 6485): #2      _parseSvgRotate (package:vector_graphics_compiler/src/svg/parsers.dart:101:28)
E/flutter ( 6485): #3      parseTransform (package:vector_graphics_compiler/src/svg/parsers.dart:49:25)
E/flutter ( 6485): #4      SvgParser._createSvgAttributes (package:vector_graphics_compiler/src/svg/parser.dart:1677:13)
E/flutter ( 6485): #5      SvgParser._readSubtree (package:vector_graphics_compiler/src/svg/parser.dart:723:30)
E/flutter ( 6485): #6      _SyncStarIterator.moveNext (dart:async-patch/async_patch.dart:528:14)
E/flutter ( 6485): #7      SvgParser._parseTree (package:vector_graphics_compiler/src/svg/parser.dart:746:28)
E/flutter ( 6485): #8      SvgParser.parse (package:vector_graphics_compiler/src/svg/parser.dart:774:5)
E/flutter ( 6485): #9      parse (package:vector_graphics_compiler/vector_graphics_compiler.dart:76:17)
E/flutter ( 6485): #10     encodeSvg (package:vector_graphics_compiler/vector_graphics_compiler.dart:141:30)
E/flutter ( 6485): #11     SvgLoader._load.<anonymous closure>.<anonymous closure> (package:flutter_svg/src/loaders.dart:41:16)
E/flutter ( 6485): #12     compute.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:18:20)
E/flutter ( 6485): #13     _RemoteRunner._run (dart:isolate:954:47)
E/flutter ( 6485): #14     _RemoteRunner._remoteExecute (dart:isolate:948:12)
E/flutter ( 6485): #15     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:17)
E/flutter ( 6485): #16     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
E/flutter ( 6485): 
E/flutter ( 6485): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Invalid double
E/flutter ( 6485): 360deg
E/flutter ( 6485): #0      double.parse (dart:core-patch/double_patch.dart:112:28)
E/flutter ( 6485): #1      parseDouble (package:vector_graphics_compiler/src/svg/numbers.dart:32:17)
E/flutter ( 6485): #2      _parseSvgRotate (package:vector_graphics_compiler/src/svg/parsers.dart:101:28)
E/flutter ( 6485): #3      parseTransform (package:vector_graphics_compiler/src/svg/parsers.dart:49:25)
E/flutter ( 6485): #4      SvgParser._createSvgAttributes (package:vector_graphics_compiler/src/svg/parser.dart:1677:13)
E/flutter ( 6485): #5      SvgParser._readSubtree (package:vector_graphics_compiler/src/svg/parser.dart:723:30)
E/flutter ( 6485): #6      _SyncStarIterator.moveNext (dart:async-patch/async_patch.dart:528:14)
E/flutter ( 6485): #7      SvgParser._parseTree (package:vector_graphics_compiler/src/svg/parser.dart:746:28)
E/flutter ( 6485): #8      SvgParser.parse (package:vector_graphics_compiler/src/svg/parser.dart:774:5)
E/flutter ( 6485): #9      parse (package:vector_graphics_compiler/vector_graphics_compiler.dart:76:17)
E/flutter ( 6485): #10     encodeSvg (package:vector_graphics_compiler/vector_graphics_compiler.dart:141:30)
E/flutter ( 6485): #11     SvgLoader._load.<anonymous closure>.<anonymous closure> (package:flutter_svg/src/loaders.dart:41:16)
E/flutter ( 6485): #12     compute.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:18:20)
E/flutter ( 6485): #13     _RemoteRunner._run (dart:isolate:954:47)
E/flutter ( 6485): #14     _RemoteRunner._remoteExecute (dart:isolate:948:12)
E/flutter ( 6485): #15     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:17)
E/flutter ( 6485): #16     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
E/flutter ( 6485): 
D/EGL_emulation( 6485): app_time_stats: avg=14.18ms min=3.18ms max=77.12ms count=48
```

**Comment by dnfield** [comment]
Can you share the SVG that causes this?

**Comment by dnfield** [comment]
There's currently no logic for handling degrees, although the CSS spec allows them.

**Comment by dnfield** [comment]
Or rather, there's no support currently for the `deg` postfix, which is the default type - if you remove that your SVG will work.

**Comment by blue492** [comment]
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);"><path fill="currentColor" d="m15.5 14l5 5l-1.5 1.5l-5-5v-.79l-.27-.28A6.471 6.471 0 0 1 9.5 16A6.5 6.5 0 0 1 3 9.5A6.5 6.5 0 0 1 9.5 3A6.5 6.5 0 0 1 16 9.5c0 1.61-.59 3.09-1.57 4.23l.28.27h.79m-6-9.5l-.55.03c-.24.52-.61 1.4-.88 2.47h2.86c-.27-1.07-.64-1.95-.88-2.47c-.18-.03-.36-.03-.55-.03M13.83 7a4.943 4.943 0 0 0-2.68-2.22c.24.53.55 1.3.78 2.22h1.9M5.17 7h1.9c.23-.92.54-1.69.78-2.22A4.943 4.943 0 0 0 5.17 7M4.5 9.5c0 .5.08 1.03.23 1.5h2.14l-.12-1.5l.12-1.5H4.73c-.15.47-.23 1-.23 1.5m9.77 1.5c.15-.47.23-1 .23-1.5s-.08-1.03-.23-1.5h-2.14a9.48 9.48 0 0 1 0 3h2.14m-6.4-3l-.12 1.5l.12 1.5h3.26a9.48 9.48 0 0 0 0-3H7.87m1.63 6.5c.18 0 .36 0 .53-.03c.25-.52.63-1.4.9-2.47H8.07c.27 1.07.65 1.95.9 2.47l.53.03m4.33-2.5h-1.9c-.23.92-.54 1.69-.78 2.22A4.943 4.943 0 0 0 13.83 12m-8.66 0a4.943 4.943 0 0 0 2.68 2.22c-.24-.53-.55-1.3-.78-2.22h-1.9Z"/></svg>`

**This is the svg which caused the error messages and I removed the style attribute. It solved the proglem**
