### ISSUE TITLE
Images stopped working with different error messages usign 2.0.2

### ISSUE THREAD

**Issue by Arcttyx** [dnfield/flutter_svg#870]
Using this simple snippet with svg images from assets:
```
@override
  Widget build(BuildContext context) {
    print(img);
    return Scaffold(
      backgroundColor: Colors.black,
      appBar: CustomHeader(
        title: (helpTitle == null)? null : Text(helpTitle!, style: const TextStyle(color: Colors.white)),
      ),
      body: 
      SingleChildScrollView(
        child: SvgPicture.asset(
          img
        )
      ),
    );
  }
```

I have a page showing different designer created svg images containing texts, icons and shapes as references on how to use the app.
Until version 1.1.6 everything worked fine. Now with Flutter 3.7.5 and flutter_svg 2.0.2 none of my images are displaying as expected.

Some of them shows for example:
```
E/flutter (10899): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: No element
E/flutter (10899): #0      List.last (dart:core-patch/growable_array.dart:348:5)
E/flutter (10899): #1      _Elements.text.computeCurrentAttributes
parser.dart:453
E/flutter (10899): #2      _Elements.text.appendText
parser.dart:464
E/flutter (10899): #3      _Elements.text
parser.dart:492
E/flutter (10899): #4      SvgParser._parseTree
parser.dart:731
E/flutter (10899): #5      SvgParser.parse
parser.dart:753
E/flutter (10899): #6      parse
vector_graphics_compiler.dart:76
E/flutter (10899): #7      encodeSvg
vector_graphics_compiler.dart:141
E/flutter (10899): #8      SvgLoader._load.<anonymous closure>.<anonymous closure>
loaders.dart:123
E/flutter (10899): #9      _testCompute
compute.dart:12
E/flutter (10899): #10     SvgLoader._load.<anonymous closure>
loaders.dart:121
E/flutter (10899): <asynchronous suspension>
```

Others:

```
E/flutter (10899): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: No element
E/flutter (10899): #0      List.last (dart:core-patch/growable_array.dart:348:5)
E/flutter (10899): #1      _Elements.text.computeCurrentAttributes
parser.dart:453
E/flutter (10899): #2      _Elements.text.appendText
parser.dart:464
E/flutter (10899): #3      _Elements.text
parser.dart:492
E/flutter (10899): #4      SvgParser._parseTree
parser.dart:731
E/flutter (10899): #5      SvgParser.parse
parser.dart:753
E/flutter (10899): #6      parse
vector_graphics_compiler.dart:76
E/flutter (10899): #7      encodeSvg
vector_graphics_compiler.dart:141
E/flutter (10899): #8      SvgLoader._load.<anonymous closure>.<anonymous closure>
loaders.dart:123
E/flutter (10899): #9      _testCompute
compute.dart:12
E/flutter (10899): #10     SvgLoader._load.<anonymous closure>
loaders.dart:121
E/flutter (10899): <asynchronous suspension>
```

flutter doctor is ok

Is it necessary to make changes to the images to make use of this version of the package?
If so, is there any guidance on how these images should be created?

I have been using the same images since last year and have not had these problems until now.
Can't share the images due to usage policies, but the same goes for some images created on websites like mediamodifier.com/svg-editor for example using simple texts and basic shapes, colors and icons

**Comment by dnfield** [comment]
Looks like a bug in text handling. Please share a svg that reproduces this.
