### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by kirill-21** [dnfield/flutter_svg#898]
### 3 _**different**_ errors:

```dart
[2023-04-05 22:47:39] [DART] [Build: 3.0.13.0] FormatException: Invalid UTF-8 byte (at offset 0); 
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1747)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351)
#2      Utf8Codec.decode (dart:convert/utf.dart:63)
#3      SvgAssetLoader.provideSvg (package:flutter_svg/src/loaders.dart:309)
#4      SvgLoader._load.<anonymous closure>.<anonymous closure> (package:flutter_svg/src/loaders.dart:124)
#5      compute.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:18)
#6      _RemoteRunner._run (dart:isolate:954)
#7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300)
#8      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
```
```dart
[2023-04-06 12:54:12] [DART] [Build: 3.0.13.0] FormatException: Missing extension byte (at offset 33); 
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1747)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351)
#2      Utf8Codec.decode (dart:convert/utf.dart:63)
#3      SvgAssetLoader.provideSvg (package:flutter_svg/src/loaders.dart:309)
#4      SvgLoader._load.<anonymous closure>.<anonymous closure> (package:flutter_svg/src/loaders.dart:124)
#5      compute.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:18)
#6      _RemoteRunner._run (dart:isolate:954)
#7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300)
#8      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
```
```dart
[2023-04-01 23:18:35] [DART] [Build: 3.0.13.0] FormatException: Unexpected extension byte (at offset 0); 
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1747)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351)
#2      Utf8Codec.decode (dart:convert/utf.dart:63)
#3      SvgAssetLoader.provideSvg (package:flutter_svg/src/loaders.dart:309)
#4      SvgLoader._load.<anonymous closure>.<anonymous closure> (package:flutter_svg/src/loaders.dart:124)
#5      compute.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:18)
#6      _RemoteRunner._run (dart:isolate:954)
#7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300)
#8      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192)

```

Hi, something similar to this issue: https://github.com/dnfield/flutter_svg/issues/888, again reported to server with PlatformDispatcher.instance.onError

**Comment by dnfield** [comment]
Argh. I fixed this but haven't published a new version since then. Let me publish.

**Comment by dnfield** [comment]
2.0.5 has the fix
