### ISSUE TITLE
Getting Unhandled Exception: FormatException: Invalid double

### ISSUE THREAD

**Issue by AppalaNaidu01** [dnfield/flutter_svg#920]
I am facing an issue with following svg:
`<svg width="16" height="16" fill="#F2C94C" viewBox="1 1 14 14" class="color-override"><path d="M8.3779 4.74233C8.14438 4.60607 7.85562 4.60607 7.6221 4.74233L5.37209 6.05513C5.14168 6.18957 5 6.4363 5 6.70311V9.34216C5 9.60897 5.14168 9.85573 5.37209 9.99016L7.6221 11.303C7.85562 11.4392 8.14438 11.4392 8.3779 11.303L10.6279 9.99016C10.8583 9.85573 11 9.60897 11 9.34216V6.70311C11 6.4363 10.8583 6.18957 10.6279 6.05513L8.3779 4.74233Z" mask="url(#hole-66.66666666666666)"></path><mask id="hole-66.66666666666666"><rect width="100%" height="100%" fill="white"></rect><circle r="4" cx="7.5" cy="8" fill="black" stroke="white" stroke-width="8" stroke-dasharray="calc(16.746666666666666) 25.12" transform="rotate(-90) translate(-16)"></circle></mask><path fill-rule="evenodd" clip-rule="evenodd" d="M7.24419 1.44066C7.71124 1.16822 8.28876 1.16822 8.75581 1.44066L13.2558 4.06566C13.7166 4.33448 14 4.82783 14 5.36133V10.6382C14 11.1717 13.7166 11.6651 13.2558 11.9339L8.75581 14.5589C8.28876 14.8313 7.71124 14.8313 7.24419 14.5589L2.74419 11.9339C2.28337 11.6651 2 11.1717 2 10.6382V5.36133C2 4.82783 2.28337 4.33448 2.74419 4.06566L7.24419 1.44066ZM8 2.73633L12.5 5.36133V10.6382L8 13.2632L3.5 10.6382V5.36133L8 2.73633Z"></path></svg>`
 

Got following error:
`[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Invalid double
100%
#0      double.parse (dart:core-patch/double_patch.dart:112:28)
#1      parseDouble (package:vector_graphics_compiler/src/svg/numbers.dart:32:17)
#2      parseDoubleWithUnits (package:vector_graphics_compiler/src/svg/numbers.dart:82:25)
#3      SvgParser.parseDoubleWithUnits (package:vector_graphics_compiler/src/svg/parser.dart:969:20)
#4      _Paths.rect (package:vector_graphics_compiler/src/svg/parser.dart:510:34)
#5      SvgParser.addShape (package:vector_graphics_compiler/src/svg/parser.dart:886:31)
#6      SvgParser.startElement (package:vector_graphics_compiler/src/svg/parser.dart:914:12)
#7      SvgParser._parseTree (package:vector_graphics_compiler/src/svg/parser.dart:764:13)
#8      SvgParser.parse (package:vector_graphics_compiler/src/svg/parser.dart:797:5)
#9      parse (package:vector_graphics_compiler/vector_graphics_compiler.dart:76:17)
#10     encodeSvg (package:vector_graphics_compiler/vec<…>`

I tried with the latest version of the library, did I used any attribute which isn't handled by this library?

**Comment by shanelau** [comment]
same error
