### ISSUE TITLE
Unhandled Exception: FormatException: Invalid double 0-70  &    Unhandled Exception: 'package:vector_graphics_compiler/src/svg/parsers.dart': Failed assertion: line 59 pos 10: 'params.length == 6': is not true.

### ISSUE THREAD

**Issue by laxit-ramani** [dnfield/flutter_svg#944]
I have added my code below which is throwing me an error every time I try to load a network SVG image in my Flutter App. The code contains my widget code, the path link to the image, and the error I am getting sequentially. I have added another Widget, code, and link as well.

I am able to open the link in a browser and load it, but unable to do it in my Flutter app.

My Code :

```
SvgPicture.network(
       path,
       height: 20,
       width: 20,
       placeholderBuilder: (context) => CircularProgressIndicator(),
)
```

Image link :   [https://cdn.coinranking.com/ryY28nXhW/ada.svg](https://cdn.coinranking.com/ryY28nXhW/ada.svg)

Error :
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Invalid double
0-70
#0      double.parse (dart:core-patch/double_patch.dart:112:28)
#1      parseDouble (package:vector_graphics_compiler/src/svg/numbers.dart:32:17)
#2      _parseSvgTranslate (package:vector_graphics_compiler/src/svg/parsers.dart:84:20)
#3      parseTransform (package:vector_graphics_compiler/src/svg/parsers.dart:49:25)
#4      SvgParser._createSvgAttributes (package:vector_graphics_compiler/src/svg/parser.dart:1686:13)
#5      SvgParser._readSubtree (package:vector_graphics_compiler/src/svg/parser.dart:685:30)
#6      _SyncStarIterator.moveNext (dart:async-patch/async_patch.dart:554:14)
#7      SvgParser._parseTree (package:vector_graphics_compiler/src/svg/parser.dart:762:28)
``` 

Image link :   [https://cdn.coinranking.com/B1N19L_dZ/bnb.svg](https://cdn.coinranking.com/B1N19L_dZ/bnb.svg)

Error :
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: 'package:vector_graphics_compiler/src/svg/parsers.dart': Failed assertion: line 59 pos 10: 'params.length == 6': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      _parseSvgMatrix (package:vector_graphics_compiler/src/svg/parsers.dart:59:10)
#3      parseTransform (package:vector_graphics_compiler/src/svg/parsers.dart:49:25)
#4      SvgParser._createSvgAttributes (package:vector_graphics_compiler/src/svg/parser.dart:1686:13)
#5      SvgParser._readSubtree (package:vector_graphics_compiler/src/svg/parser.dart:685:30)
#6      _SyncStarIterator.moveNext (dart:async-patch/async_patch.dart:554:14)
#7      SvgParser._parseTree (package:vector_graphics_compiler/src/svg/parser.dart:762:28)
#8      SvgParser.parse (package:vector_graphics_compiler/src/svg/parser.dart:797:5)
#9      parse (package:vector_graphics_compiler/vector_graphics_compiler.dart:76:17)
#10     encodeSvg (package:vector_graphics_compiler/vector_graphics_compiler.dart:143:5)
#11     SvgLoader._load.<anonymous closure>.<anonymous closure> (package:flutter_svg/src/loaders.dart:137:14)
#12     _testCompute (package:flutter_svg/src/utilities/compute.dart:12:38)
#13     SvgLoader._load.<anonymous closure> (package:flutter_svg/src/loaders.dart:135:21)
```

**Comment by dnfield** [comment]
These are cases where some `transform` attribute parameters are missing whitespace the spec implies should be there. But Chrome tolerates this.

The case of missing whitespace before a `-` is pretty easy to handle. The multiple decimal point one is a little more troubling.
