### ISSUE TITLE
XmlParserException

### ISSUE THREAD

**Issue by kirill-21** [dnfield/flutter_svg#949]
[2023-06-21 16:50:25] [DART] [Build: 3.0.21.0] XmlParserException: ">" expected at 5:23; #0      XmlEventIterator.moveNext (package:xml/src/xml_events/iterator.dart:42)#1      SvgParser._readSubtree (package:vector_graphics_compiler/src/svg/parser.dart:671)#2      _SyncStarIterator.moveNext (dart:async-patch/async_patch.dart:554)#3      SvgParser._parseTree (package:vector_graphics_compiler/src/svg/parser.dart:762)#4      SvgParser.parse (package:vector_graphics_compiler/src/svg/parser.dart:797)#5      parse (package:vector_graphics_compiler/vector_graphics_compiler.dart:76)#6      encodeSvg (package:vector_graphics_compiler/vector_graphics_compiler.dart:143)#7      SvgLoader._load.<anonymous closure>.<anonymous closure> (package:flutter_svg/src/loaders.dart:137)#8      compute.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:19)#9      _RemoteRunner._run (dart:isolate:1021)#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299)#11     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)

Have no idea how it happens, just an unhandled exception from logs on server

**Comment by dnfield** [comment]
You're giving it invalid XML. Please share an SVG that causes this.

**Comment by kirill-21** [comment]
I changed literally nothing in my app, just updated flutter_svg version to the latest one and issue appeared, I have hundreds of SVGs in my app

**Comment by dnfield** [comment]
It's quite possible that the XML parsing library got a bit more strict, or that the way flutter_svg is using it got a little more strict. 

If you can share an SVG that is valid XML and should parse I can try to look at this more - but if in fact you're feeding it invalid XML that used to parse but now doesn't I don't really think there's much I can do.
