### ISSUE TITLE
Inkscape gradients not rendering

### ISSUE THREAD

**Issue by hash404** [dnfield/flutter_svg#97]
Gradients made in Inkscape don't always render properly with flutter_svg.

Here is what the SVG looks like with version 0.9.0+1 of flutter_svg:

<img width="130" alt="" src="https://user-images.githubusercontent.com/36620537/50733471-1f7bd100-11e2-11e9-91f8-a66c8a5b1793.png">

Here is what it should look like (verified in web browser, Firefox and Android Studio's SVG preview):

<img width="424" alt="" src="https://user-images.githubusercontent.com/36620537/50733472-24d91b80-11e2-11e9-8f21-be910981532b.png">

Inkscape version:
```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:xlink="http://www.w3.org/1999/xlink"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   width="356.78598"
   height="356.78598"
   viewBox="0 0 94.399622 94.399627"
   version="1.1"
   id="svg8"
   inkscape:version="0.92.2 5c3e80d, 2017-08-06"
   sodipodi:docname="gradient.svg">
  <defs
     id="defs2">
    <linearGradient
       inkscape:collect="always"
       id="linearGradient829">
      <stop
         style="stop-color:#ff02ce;stop-opacity:1"
         offset="0"
         id="stop825" />
      <stop
         style="stop-color:#ffef3a;stop-opacity:1"
         offset="1"
         id="stop827" />
    </linearGradient>
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient829"
       id="linearGradient831"
       x1="-157.99403"
       y1="122.75297"
       x2="-9.071434"
       y2="122.75297"
       gradientUnits="userSpaceOnUse" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient829"
       id="linearGradient916"
       gradientUnits="userSpaceOnUse"
       x1="-157.99403"
       y1="122.75297"
       x2="-9.071434"
       y2="122.75297" />
  </defs>
  <sodipodi:namedview
     id="base"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageopacity="0.0"
     inkscape:pageshadow="2"
     inkscape:zoom="0.7"
     inkscape:cx="116.40809"
     inkscape:cy="239.7796"
     inkscape:document-units="mm"
     inkscape:current-layer="g914"
     showgrid="false"
     inkscape:window-width="1440"
     inkscape:window-height="818"
     inkscape:window-x="0"
     inkscape:window-y="1"
     inkscape:window-maximized="1"
     units="px"
     fit-margin-top="0"
     fit-margin-left="0"
     fit-margin-right="0"
     fit-margin-bottom="0" />
  <metadata
     id="metadata5">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title></dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <g
     inkscape:label="Layer 1"
     inkscape:groupmode="layer"
     id="layer1"
     transform="translate(2.9777116,-102.81465)">
    <g
       id="g884">
      <g
         id="g914"
         transform="matrix(0.63388377,0,0,0.63388377,97.172147,72.203346)">
        <circle
           r="74.461304"
           cy="122.75297"
           cx="-83.532738"
           id="path815"
           style="opacity:1;fill:url(#linearGradient916);fill-opacity:1;stroke:none;stroke-width:0.39687499;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1" />
      </g>
    </g>
  </g>
</svg>
```

Compressed version (without any Inkscape metadata):

```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 94.4 94.4">
  <defs>
    <linearGradient id="a">
      <stop offset="0" stop-color="#ff02ce"/>
      <stop offset="1" stop-color="#ffef3a"/>
    </linearGradient>
    <linearGradient id="b" x1="-157.994" x2="-9.071" y1="122.753" y2="122.753" gradientUnits="userSpaceOnUse" xlink:href="#a"/>
  </defs>
  <circle cx="-83.533" cy="122.753" r="74.461" fill="url(#b)" transform="matrix(.63388 0 0 .63388 100.15 -30.611)"/>
</svg>
```

Both versions don't work with the current build but can't figure out why some other SVGs with gradients work fine.

Issue related to https://github.com/dnfield/flutter_svg/issues/49 and https://github.com/dnfield/flutter_svg/issues/4

**Comment by dnfield** [comment]
It's because the gradients have references to each other, which isn't supported (yet).

See https://github.com/dnfield/flutter_svg/issues/68

**Comment by hash404** [comment]
Is there a workaround for this? Even the simplest gradients made in Inkscape with two stops have this issue, so it would be hard to manually change everything for the bigger SVG files.

**Comment by dnfield** [comment]
I can look at supporting this - for now, unfortunately, it'd require manually updating the SVG.

I'm not sure if Inkscape has a setting control this - I have a feeling it doesn't though.

**Comment by dnfield** [comment]
FYI - your compressed version would go from:

```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 94.4 94.4">
  <defs>
    <linearGradient id="a">
      <stop offset="0" stop-color="#ff02ce"/>
      <stop offset="1" stop-color="#ffef3a"/>
    </linearGradient>
    <linearGradient id="b" x1="-157.994" x2="-9.071" y1="122.753" y2="122.753" gradientUnits="userSpaceOnUse" xlink:href="#a"/>
  </defs>
  <circle cx="-83.533" cy="122.753" r="74.461" fill="url(#b)" transform="matrix(.63388 0 0 .63388 100.15 -30.611)"/>
</svg>
```

to

```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 94.4 94.4">
  <defs>
    <linearGradient id="a" x1="-157.994" x2="-9.071" y1="122.753" y2="122.753" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#ff02ce"/>
      <stop offset="1" stop-color="#ffef3a"/>
    </linearGradient>
  </defs>
  <circle cx="-83.533" cy="122.753" r="74.461" fill="url(#a)" transform="matrix(.63388 0 0 .63388 100.15 -30.611)"/>
</svg>
```

**Comment by hash404** [comment]
Thank you - I have quite a few Inkscape SVGs, so a fix in the code would be good.

**Comment by dnfield** [comment]
Implemented in dd44ee7 - can you try that revision and make sure it's working for you?

**Comment by hash404** [comment]
Tried it on the more complex SVGs which haven't been working.

This is the error I'm getting

```
flutter: ══╡ EXCEPTION CAUGHT BY SVG ╞═══════════════════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown resolving a single-frame picture stream:
flutter: The getter 'colors' was called on null.
flutter: Receiver: null
flutter: Tried calling: colors
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
flutter: #1      _Elements.linearGradient (package:flutter_svg/src/svg/parser_state.dart:272:25)
flutter: #2      SvgParserState.parse (package:flutter_svg/src/svg/parser_state.dart:579:28)
flutter: <asynchronous suspension>
flutter: #3      SvgParser.parse (package:flutter_svg/parser.dart:14:58)
flutter: <asynchronous suspension>
flutter: #4      Svg.fromSvgString (package:flutter_svg/svg.dart:110:25)
flutter: <asynchronous suspension>
flutter: #5      Svg.svgPictureStringDecoder (package:flutter_svg/svg.dart:72:36)
flutter: <asynchronous suspension>
flutter: #6      SvgPicture.svgStringDecoder.<anonymous closure> (package:flutter_svg/svg.dart:444:15)
flutter: #7      AssetBundlePictureProvider._loadAsync (package:flutter_svg/src/picture_provider.dart:426:18)
flutter: <asynchronous suspension>
flutter: #8      AssetBundlePictureProvider.load (package:flutter_svg/src/picture_provider.dart:408:43)
flutter: #9      PictureProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter_svg/src/picture_provider.dart:307:57)
flutter: #10     PictureCache.putIfAbsent (package:flutter_svg/src/picture_cache.dart:67:22)
flutter: #11     PictureProvider.resolve.<anonymous closure> (package:flutter_svg/src/picture_provider.dart:307:34)
flutter: #12     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
flutter: #13     PictureProvider.resolve (package:flutter_svg/src/picture_provider.dart:305:17)
flutter: #14     _SvgPictureState._resolveImage (package:flutter_svg/svg.dart:542:10)
flutter: #15     _SvgPictureState.didChangeDependencies (package:flutter_svg/svg.dart:516:5)
flutter: #16     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:12)
flutter: #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
```

Will try and find a SVG I can share with the same issue to repro

**Comment by dnfield** [comment]
Thanks for all the examples!

I'll take a look.

**Comment by dnfield** [comment]
That last one is very fixable.

The other two are bad news.  I've improved the error message for those cases, but this library expects references to be defined __before__ they're used - otherwise we have to start keeping more things around in memory.

I have an idea about how I could maybe tolerate that for this case, but for now I've improved the error message.  If you move  the element up towards the top of the document, Inkscape shouldn't move it again on you.

**Comment by hash404** [comment]
Thanks for the radial gradient fix.

Manually ordering defs fixes the issue for the first two cases as well.

**Comment by dnfield** [comment]
I'm going to publish this for now, and I'll open a new issue for tracking whether we can get some support for out-of-order definitions.

**Comment by dnfield** [comment]
published as v0.10.1
